### PR TITLE
stop using deprecated ffmpeg constants

### PR DESCRIPTION
**Pull request by s-ol**

### CODE REVIEW

**Comment by kritzikratzi** [comment]
`AVMediaType` creates conflicts on MacOSX, because it also exists in the global namespace in AVFoundation, and it seems OF always pulls that in. i'll see tomorrow if i can work around it in a meaningful way.

**Comment by s-ol** [comment]
@kritzikratzi maybe there should just be a little `#ifdef __APPLE__` or whatever guard?

**Comment by kritzikratzi** [comment]
yes, something along those lines. well, enough for today. tomorrow is another day :)

**Comment by kritzikratzi** [comment]
can you check if the latest head in the of10 branch works for you? 

i forgot to merge before, here is the interesting commit: 
https://github.com/kritzikratzi/ofxAvCodec/commit/4878c78cd08bed1f441ead7c756bdd0279ef17a4

**Comment by s-ol** [comment]
@kritzikratzi sorry, didn't have time to do another test run on Linux today. I won't be around a PC until next wednesday or so, so let's take a little break :slightly_smiling_face:

**Comment by s-ol** [comment]
@kritzikratzi builds cleanly :slightly_smiling_face: I updated kritzikratzi/Oscilloscope#68 with the latest of10 commit.

**Pull request closed without merging**
